### ISSUE TITLE
Exchange to xarray progress tracking

### ISSUE THREAD

**Issue by DocOtak** [cchdo/hydro#5]
The [Exchange data class](https://github.com/cchdo/hydro/blob/942d0eff7e0c1b64067f017174fd8915e5919750/hydro/exchange.py#L334) seems pretty OK now that I've refamiliarized myself with it, or I just remember my own thoughts better when I was writing it. Regardless, focus is now on making the [`to_xarray()`](https://github.com/cchdo/hydro/blob/942d0eff7e0c1b64067f017174fd8915e5919750/hydro/exchange.py#L421) method work well. It sorta works right now, but doesn't produce very useful output. Here is a list of current issues:

- [x] Currently ~no~ some attributes are added to the xr.Dataset, should start with whp_name, whp_unit, units, standard name, etc... so that data are "usable": Update 2020-04-20, attributes are being added, need to do some verification that they are as complete as they can be without human intervention.
- [x] Everything that can label a point (EXPOCODE, STNNBR, etc..) should be included in the CF "coordinates" attribute.
- [x] qc and error variables need to be connected to their "parent" variable using the CF "ancillary_variables" attribute
  - [x] QC
  - [x] error
- [x] need to include error data (aka uncertainty)
- [x]  Date and Time need to be combined into a single datetime variable, currently they are output as two separate string variables.
  - [ ]  need to decide if the epoch should be fixed for the library (e.g. days since 1900-01-01), or use the start date of each cruise.
- [ ] Need to handle individual bottle trip XYT coordinates, this has the same issue as the date time above.
- [x] Some variables apply to only the cast/profile and not to every sampling level: these include EXPOCODE, STNNBR, CASTNO, LATITUDE, LONGITUDE, DATE, TIME, geotraces event numbers, instrument ID, etc... these should be collapsed to 1D vars.
  - [x] should check that they actually have the same value per cast, this is guaranteed in exchange CTD data, but not with exchange BOTTLE data.
- [x] Missing values in string data (e.g. BTLNBR) currently have the string `"None"` this should be swapped to some _FillValue or an empty string or whatever the library supports.
- [x] Need to actually include flag variables in the Dataset, this was actually done before I wrote this issue, but I wanted at least one check mark checked to feel better.
- [x] Flag variables need the appropriate flag definitions added in a [CF compliant way](http://cfconventions.org/cf-conventions/cf-conventions.html#flags).

**Comment by DocOtak** [comment]
Closing this in favor of #2 #7 and #8 for the lingering "first version" issues.
