### ISSUE TITLE
Exchange to .csv tracking

### ISSUE THREAD

**Issue by mvkovatch3** [cchdo/hydro#9]
- [x] Iterate using `self.iter_profiles` instead of data lines
- [x] Use params as `WHPName` objects instead of `str`
- [x] Report [proper precision](https://github.com/cchdo/params/blob/8afcdee324e1ef24a040a0c895533d25ae2249af/cchdo/params/__init__.py#L57-L58) for each param 
- [x] Output as bytes
- [x] Expand write options
    - [x] no arguments
    - [x] to open file: `with open(...) as f: data.to_exchange(f)`
    - [x] to path: `data.to_exchange("/some/path"`
    - [x] to zip (CTD only)
- [x] CTD data handling
    - [x] `Exchange` object with multiple casts to single cast files
    - [x] optional output of zip or exploded out
    - [x] CTD file header
- [x] Add handling for file comments
- [ ] Edge cases
    - [x] File without `TIME` (param not required)
    - [x] Handling for alphanumeric `STNNBR` (currently only handles int)
- [ ] Formatting for CTD filenames? CCHDO has no naming convention
- [ ] Add code comments

**Comment by DocOtak** [comment]
Closed by 6506c2ee4b8f5aac3fa2e6a813ce47c351710aed to 88edb7043d684b91b7456faba7dd43033ef827a0

There might be some lingering edge cases once we have the optical parameters working, but not there yet, I've been trying to find a file where the only problem is lack of param defs for things like CDOMxxx where xxx is a wavelength.
